events {}

http {
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log warn;
  
  upstream backend_clusters {
    least_conn;
    server backend:5000 weight=3 max_fails=3 fail_timeout=10s;
  }

  # 1. Дефолтный сервер (обрабатывает запросы по IP и левым доменам)
  server {
    listen 80 default_server;

    location = /metrics {
        stub_status on;
        access_log off;
    }

    location / {
        return 444;
    }
  }

  # 2. Редирект со старого сайта
  server {
        listen 80;
        server_name old-site.ru www.old-site.ru;
        location / {
            return 301 https://main_app.com$request_uri;
        }
  }

  # 3. Основной сервер
  server {
    listen 80;
    server_name localhost main_app.com nginx;

    location = /metrics {
        stub_status on;
        access_log off;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location ~* \.(jpg|png)$ {
        root /usr/share/nginx/html;
        expires 30d;
        access_log off;
    }

    location /api {
        proxy_pass http://backend_clusters;
        proxy_set_header Host $host;
        proxy_set_header X-Real_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}